### ISSUE TITLE
After installing on_boot common container and cniupdates can no longer get into unifi-os shell container

### ISSUE THREAD

**Issue by justfly1111** [boostchicken/udm-utilities#241]
**Describe the bug**
heres a copy and paste of me attemting unifi-os shell:
# ls /mnt/data
dpi-tracer    lost+found    podman        system        udm-le        unifi-os
etc-pihole    on_boot.d     rclone        traces        ui-db
log           pihole        ssh           udapi-config  ulcmd
# ls /mnt/data/podman
cni      storage
# ls /mnt/data/.cache
cni-plugins    conmon-2.0.29  podman-3.3.0   runc-1.0.2
# ls /mnt/data/.cache/cni-plugins
cni-plugins-linux-arm64-installed.tgz         cni-plugins-linux-arm64-latest.tgz.sha256
cni-plugins-linux-arm64-installed.tgz.sha256  cni-plugins-linux-arm64-v1.0.1.tgz
cni-plugins-linux-arm64-latest.tgz            cni-plugins-linux-arm64-v1.0.1.tgz.sha256
# podman ps
CONTAINER ID  IMAGE                      COMMAND     CREATED     STATUS         PORTS       NAMES
bda0986a44f0  localhost/unifi-os:latest  /sbin/init  4 days ago  Up 2 days ago              unifi-os
# uname -a
Linux Eleven11-UDM-pro 4.19.152-al-linux-v10.2.0-v1.11.0-14.3859-c147cc8 #1 SMP Fri Aug 13 07:35:29 UTC 2021 aarch64 GNU/Linux
# unifi-os shell
WARN[0000] Failed to add conmon to cgroupfs sandbox cgroup: open /sys/fs/cgroup/libpod_parent/conmon/cpuset.cpus: open /sys/fs/cgroup/libpod_parent/conmon/cpuset.cpus.effective: no such file or directory 
Error: OCI runtime error: panic: expected "name=systemd" path to be unified path "/sys/fs/cgroup/devices/libpod_parent/libpod-bda0986a44f05f412bfa6cf24c3c5baf0cb6225e2a98a199d0125624dd636ed8", got "/sys/fs/cgroup/systemd/libpod_parent/libpod-bda0986a44f05f412bfa6cf24c3c5baf0cb6225e2a98a199d0125624dd636ed8"

goroutine 1 [running]:
github.com/opencontainers/runc/libcontainer.getUnifiedPath(0x40002c7290, 0x555c403400, 0x0)
	github.com/opencontainers/runc/libcontainer/factory_linux.go:59 +0x2cc
github.com/opencontainers/runc/libcontainer.cgroupfs2.func1(0x40002617a0, 0x40002c7290, 0x4a, 0x7fcf360edf)
	github.com/opencontainers/runc/libcontainer/factory_linux.go:111 +0x30
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).Load(0x400026a090, 0x7fcf360edf, 0x40, 0x0, 0x0, 0x1, 0x8)
	github.com/opencontainers/runc/libcontainer/factory_linux.go:321 +0x14c
main.getContainer(0x4000288160, 0x555c413e78, 0x8, 0x1, 0x4000253366)
	github.com/opencontainers/runc/utils_linux.go:89 +0x9c
main.execProcess(0x4000288160, 0x0, 0x0, 0x0)
	github.com/opencontainers/runc/exec.go:114 +0x30
main.glob..func5(0x4000288160, 0x555c8373c0, 0x40002534f8)
	github.com/opencontainers/runc/exec.go:104 +0x6c
github.com/urfave/cli.HandleAction(0x555c504d60, 0x555c5b1bc8, 0x4000288160, 0x4000288160, 0x0)
	github.com/urfave/cli@v1.22.1/app.go:523 +0x124
github.com/urfave/cli.Command.Run(0x555c40ff3e, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x555c427b5a, 0x28, 0x0, ...)
	github.com/urfave/cli@v1.22.1/command.go:174 +0x408
github.com/urfave/cli.(*App).Run(0x400023e000, 0x40000200e0, 0xe, 0xe, 0x0, 0x0)
	github.com/urfave/cli@v1.22.1/app.go:276 +0x588
main.main()
	github.com/opencontainers/runc/main.go:163 +0xa78
# 
**To Reproduce**
instll udm-utilities
on_boot
common-container
and cniupdate

**Expected behavior**
to be able to get into unifi-os container 
**Screenshots**
copy and paste
# ls /mnt/data
dpi-tracer    lost+found    podman        system        udm-le        unifi-os
etc-pihole    on_boot.d     rclone        traces        ui-db
log           pihole        ssh           udapi-config  ulcmd
# ls /mnt/data/podman
cni      storage
# ls /mnt/data/.cache
cni-plugins    conmon-2.0.29  podman-3.3.0   runc-1.0.2
# ls /mnt/data/.cache/cni-plugins
cni-plugins-linux-arm64-installed.tgz         cni-plugins-linux-arm64-latest.tgz.sha256
cni-plugins-linux-arm64-installed.tgz.sha256  cni-plugins-linux-arm64-v1.0.1.tgz
cni-plugins-linux-arm64-latest.tgz            cni-plugins-linux-arm64-v1.0.1.tgz.sha256
# podman ps
CONTAINER ID  IMAGE                      COMMAND     CREATED     STATUS         PORTS       NAMES
bda0986a44f0  localhost/unifi-os:latest  /sbin/init  4 days ago  Up 2 days ago              unifi-os
# uname -a
Linux Eleven11-UDM-pro 4.19.152-al-linux-v10.2.0-v1.11.0-14.3859-c147cc8 #1 SMP Fri Aug 13 07:35:29 UTC 2021 aarch64 GNU/Linux
# unifi-os shell
WARN[0000] Failed to add conmon to cgroupfs sandbox cgroup: open /sys/fs/cgroup/libpod_parent/conmon/cpuset.cpus: open /sys/fs/cgroup/libpod_parent/conmon/cpuset.cpus.effective: no such file or directory 
Error: OCI runtime error: panic: expected "name=systemd" path to be unified path "/sys/fs/cgroup/devices/libpod_parent/libpod-bda0986a44f05f412bfa6cf24c3c5baf0cb6225e2a98a199d0125624dd636ed8", got "/sys/fs/cgroup/systemd/libpod_parent/libpod-bda0986a44f05f412bfa6cf24c3c5baf0cb6225e2a98a199d0125624dd636ed8"

goroutine 1 [running]:
github.com/opencontainers/runc/libcontainer.getUnifiedPath(0x40002c7290, 0x555c403400, 0x0)
	github.com/opencontainers/runc/libcontainer/factory_linux.go:59 +0x2cc
github.com/opencontainers/runc/libcontainer.cgroupfs2.func1(0x40002617a0, 0x40002c7290, 0x4a, 0x7fcf360edf)
	github.com/opencontainers/runc/libcontainer/factory_linux.go:111 +0x30
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).Load(0x400026a090, 0x7fcf360edf, 0x40, 0x0, 0x0, 0x1, 0x8)
	github.com/opencontainers/runc/libcontainer/factory_linux.go:321 +0x14c
main.getContainer(0x4000288160, 0x555c413e78, 0x8, 0x1, 0x4000253366)
	github.com/opencontainers/runc/utils_linux.go:89 +0x9c
main.execProcess(0x4000288160, 0x0, 0x0, 0x0)
	github.com/opencontainers/runc/exec.go:114 +0x30
main.glob..func5(0x4000288160, 0x555c8373c0, 0x40002534f8)
	github.com/opencontainers/runc/exec.go:104 +0x6c
github.com/urfave/cli.HandleAction(0x555c504d60, 0x555c5b1bc8, 0x4000288160, 0x4000288160, 0x0)
	github.com/urfave/cli@v1.22.1/app.go:523 +0x124
github.com/urfave/cli.Command.Run(0x555c40ff3e, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x555c427b5a, 0x28, 0x0, ...)
	github.com/urfave/cli@v1.22.1/command.go:174 +0x408
github.com/urfave/cli.(*App).Run(0x400023e000, 0x40000200e0, 0xe, 0xe, 0x0, 0x0)
	github.com/urfave/cli@v1.22.1/app.go:276 +0x588
main.main()
	github.com/opencontainers/runc/main.go:163 +0xa78
# 
**UDM Information**
 uname -a 

Linux Eleven11-UDM-pro 4.19.152-al-linux-v10.2.0-v1.11.0-14.3859-c147cc8 #1 SMP Fri Aug 13 07:35:29 UTC 2021 aarch64 GNU/Linux
**Additional context**
also am submitting a diff bug issue about needing help getting pihole container to run

**Comment by justfly1111** [comment]
it seems like im getting the following error no matter which script i try to start and or use

WARN[0000] Failed to add conmon to cgroupfs sandbox cgroup: open /sys/fs/cgroup/libpod_parent/conmon/cpuset.cpus: open /sys/fs/cgroup/libpod_parent/conmon/cpuset.cpus.effective: no such file or directory 
Error: OCI runtime error: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: bpf_prog_query(BPF_CGROUP_DEVICE) failed: function not implemented
#

**Comment by GhostlyCrowd** [comment]
This is the same issue as https://github.com/boostchicken/udm-utilities/issues/233

I dont think its fixed yet,  some one said they had it working and the maintainer added something to the podman script but it still seems to be broken since youre having the same issue. I would report in that issue as well

**Comment by justfly1111** [comment]
yeah you either have to not update podman or or fallback to the 1.10 firmware and it works but nothing else got it to work

**Comment by boostchicken** [comment]
I have no way to fix this, it is just an incompatibility that UI made
